spring:
  application:
    name: sharding-service

sharding:
  jdbc:
    datasource:
      names: ds0,ds1,ds0_slave0,ds0_slave1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 888888
        maxPoolSize: 20
      ds0_slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0_slave0?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 888888
        maxPoolSize: 20
      ds0_slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds0_slave1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 888888
        maxPoolSize: 20
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds1?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
        username: root
        password: 888888
        maxPoolSize: 20
    config:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: id
            algorithm-expression: ds_$->{ id % 2 }
        tables:
          user:
            actual-data-nodes: ds_${0..1}.user_$->{0..3}
            table-strategy:
              standard:
                sharding-column: id
                precise-algorithm-class-name: com.my.sharding.config.IdPreciseShardingAlgorithm
        master-slave-rules:
          ds_0:
            master-data-source-name: ds0
            slave-data-source-names: ds0_slave0, ds0_slave1
          ds_1:
            master-data-source-name: ds1
            slave-data-source-names: ds0_slave0, ds0_slave1
      props:
        sql:
          show: true

server:
  port: 8001

mybatis:
  typeAliasesPackage: com.my
  mapper-locations: classpath:mapper/*Mapper.xml
